### ISSUE TITLE
Previously working migration now fails

### ISSUE THREAD

**Issue by hanneskaeufler** [luckyframework/lucky_migrator#84]
After upgrading to crystal 0.24.1 and bumping all the lucky versions
```yaml
  lucky_migrator:
    github: luckyframework/lucky_migrator
    version: ~> 0.4.0
```
one migration of my blog app doesn't run anymore. It fails with `column "slug" of relation "posts" does not exist`.

The migration that fails is:
```crystal
class AddSlugToPosts::V20171220204327 < LuckyMigrator::Migration::V1
  def migrate
    alter :posts do
      add slug : String?
    end

    # the following is the offending line, if I remove it, it works
    execute "UPDATE posts SET slug = regexp_replace(lower(title), '\\s', '-', 'g')"
  end
end
```

Looks like something changed regarding the sequence of adding the column and executing the raw sql?
